spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barquito_dev
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    com.barquito: DEBUG
    org.flywaydb: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLWRldi1zZWNyZXQtdGhhdC1pcy0yNTYtYml0cy1sb25nLW9rYXk}

app:
  cors:
    allowed-origins: http://localhost:5173
